DROP TABLE IF EXISTS "Address_Tbl";
CREATE TABLE "Address_Tbl" ("Person_ID" INTEGER NOT NULL , "Address_Type" VARCHAR NOT NULL , "Address1" VARCHAR, "Address2" VARCHAR, "City" VARCHAR, "State" VARCHAR, "Zip" VARCHAR, "Country" VARCHAR, PRIMARY KEY ("Person_ID", "Address_Type"));
DROP TABLE IF EXISTS "Address_type_Tbl";
CREATE TABLE "Address_type_Tbl" ("Address_Type" VARCHAR PRIMARY KEY  NOT NULL ,"Address_Type_Descr" VARCHAR NOT NULL  DEFAULT (null) );
INSERT INTO "Address_type_Tbl" VALUES('PH','Primary Home');
INSERT INTO "Address_type_Tbl" VALUES('SH','Secondary Home');
INSERT INTO "Address_type_Tbl" VALUES('WK','Work');
INSERT INTO "Address_type_Tbl" VALUES('BL','Billing');
DROP TABLE IF EXISTS "Certificate_Course_Tbl";
CREATE TABLE "Certificate_Course_Tbl" ("Certificate_ID" INTEGER NOT NULL , "Course_ID" INTEGER NOT NULL , PRIMARY KEY ("Certificate_ID", "Course_ID"));
DROP TABLE IF EXISTS "Certificate_Tbl";
CREATE TABLE "Certificate_Tbl" ("Certificate_ID" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "Name" VARCHAR, "Credits" INTEGER, "Start_Date" DATETIME, "End_Date" DATETIME);
DROP TABLE IF EXISTS "Class_Tbl";
CREATE TABLE "Class_Tbl" ("Class_ID" INTEGER PRIMARY KEY  NOT NULL  DEFAULT (null) ,"Course_ID" INTEGER NOT NULL ,"Instructor_ID" INTEGER NOT NULL ,"Location_ID" INTEGER NOT NULL ,"Start_Date" DATETIME,"End_Date" DATETIME);
DROP TABLE IF EXISTS "Contact_Tbl";
CREATE TABLE "Contact_Tbl" ("Person_ID" INTEGER NOT NULL , "Contact_Type" VARCHAR NOT NULL , "Information" VARCHAR, "Primary_Contact" BOOL, PRIMARY KEY ("Person_ID", "Contact_Type"));
DROP TABLE IF EXISTS "Contact_Type_Tbl";
CREATE TABLE "Contact_Type_Tbl" ("Contact_Type" VARCHAR PRIMARY KEY  NOT NULL , "Contact_Type_Descr" VARCHAR);
INSERT INTO "Contact_Type_Tbl" VALUES('PHHM','Phone - Home');
INSERT INTO "Contact_Type_Tbl" VALUES('PHCL','Phone - Cell');
INSERT INTO "Contact_Type_Tbl" VALUES('PHWK','Phone - Work');
INSERT INTO "Contact_Type_Tbl" VALUES('EMHM','Email - Home');
INSERT INTO "Contact_Type_Tbl" VALUES('EMWK','Email - Work');
INSERT INTO "Contact_Type_Tbl" VALUES('EMSC','Email - School');
INSERT INTO "Contact_Type_Tbl" VALUES('IMFB','Instant Messenger - Facebook');
INSERT INTO "Contact_Type_Tbl" VALUES('IMLV','Instant Messenger - Microsoft Live');
DROP TABLE IF EXISTS "Course_Price_Tbl";
CREATE TABLE "Course_Price_Tbl" ("CourseID" INTEGER, "Effective_Date" DATETIME, "Price" NUMERIC);
DROP TABLE IF EXISTS "Course_Tbl";
CREATE TABLE "Course_Tbl" ("Course_ID" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "Course_Type" VARCHAR, "Name" VARCHAR, "Status" VARCHAR, "Enroll_Capacity" INTEGER);
DROP TABLE IF EXISTS "Course_Type_Tbl";
CREATE TABLE "Course_Type_Tbl" ("Course_Type" VARCHAR PRIMARY KEY  NOT NULL ,"Course_Type_Descr" VARCHAR DEFAULT (null) );
INSERT INTO "Course_Type_Tbl" VALUES('DB','Database');
INSERT INTO "Course_Type_Tbl" VALUES('SA','Systems Analysis');
INSERT INTO "Course_Type_Tbl" VALUES('Web','Web Development');
INSERT INTO "Course_Type_Tbl" VALUES('PGM','Basic Programming');
INSERT INTO "Course_Type_Tbl" VALUES('MOB','Mobile Development');
INSERT INTO "Course_Type_Tbl" VALUES('SIM','Simulation Development');
INSERT INTO "Course_Type_Tbl" VALUES('WIN','Windows Development');
INSERT INTO "Course_Type_Tbl" VALUES('OS','System Support');
DROP TABLE IF EXISTS "Employee_Tbl";
CREATE TABLE "Employee_Tbl" ("Person_ID" INTEGER NOT NULL , "Employee_Type" VARCHAR NOT NULL , "Employee_Title" VARCHAR, "Hire_Date" DATETIME, "Termination_Date" DATETIME, PRIMARY KEY ("Person_ID", "Employee_Type"));
DROP TABLE IF EXISTS "Employee_Type_Tbl";
CREATE TABLE "Employee_Type_Tbl" ("Employee_Type" VARCHAR PRIMARY KEY  NOT NULL ,"Employee_Type_Descr" VARCHAR DEFAULT (null) );
DROP TABLE IF EXISTS "Location_Tbl";
CREATE TABLE "Location_Tbl" ("Location_ID" INTEGER PRIMARY KEY  NOT NULL ,"Location_Descr" VARCHAR DEFAULT (null) );
INSERT INTO "Location_Tbl" VALUES(1,'Main Office');
INSERT INTO "Location_Tbl" VALUES(2,'Online');
DROP TABLE IF EXISTS "Person_Tbl";
CREATE TABLE "Person_Tbl" ("Person_ID" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "First_Name" VARCHAR, "Middle_Name" VARCHAR, "Last_Name" VARCHAR, "Birth_Date" DATETIME);
INSERT INTO "Person_Tbl" VALUES(1,'Kyle','Keith','Loewenhagen','09/01/1970');
INSERT INTO "Person_Tbl" VALUES(2,'Jennifer','Elaine','Diederich','08/02/1976');
DROP TABLE IF EXISTS "Reg_Code_Tbl";
CREATE TABLE "Reg_Code_Tbl" ("Reg_Code" VARCHAR PRIMARY KEY  NOT NULL ,"Reg_Code_Descr" VARCHAR DEFAULT (null) );
INSERT INTO "Reg_Code_Tbl" VALUES('R','Registered');
INSERT INTO "Reg_Code_Tbl" VALUES('W','Withdrawn');
DROP TABLE IF EXISTS "Student_Certificate_Tbl";
CREATE TABLE "Student_Certificate_Tbl" ("Person_ID" INTEGER NOT NULL , "Certificate_ID" INTEGER NOT NULL , "Enrollment_Date" DATETIME, "Completion_Date" DATETIME, PRIMARY KEY ("Person_ID", "Certificate_ID"));
DROP TABLE IF EXISTS "Student_Class_Tbl";
CREATE TABLE "Student_Class_Tbl" ("Class_ID" INTEGER PRIMARY KEY  NOT NULL  DEFAULT (null) ,"Student_ID" INTEGER NOT NULL ,"Registration_Date" DATETIME,"Reg_Code" VARCHAR);
